version: '3'

services:
  client:
    image: metaprojeto-exemplo-client
    ports:
      - "8080:80"
    build:
      context: ./MetaProjetoExemplo.SpaClient/
    networks:
      - exampleapp
  # API
  api:
    image: metaprojeto-exemplo-api
    build:
      context: .
      dockerfile: ./MetaProjetoExemplo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:5000"
      DATABASE_SERVER: "database"
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - exampleapp
  database:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123##"
    networks:
      - exampleapp

networks: 
    exampleapp:
        driver: bridge