version: '3'

services:
  # API
  api:
    image: metaprojeto-exemplo-api
    build:
      context: .
      dockerfile: ./MetaProjetoExemplo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    networks:
      - exampleapp
    depends_on:
      - database

  database:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123##"
    networks:
      - exampleapp

networks: 
    exampleapp:
        driver: bridge